refactor: variable name, error handling, etc.

diff --git a/mp3_vol_adjustment b/mp3_vol_adjustment
--- a/mp3_vol_adjustment
+++ b/mp3_vol_adjustment
@@ -1,38 +1,57 @@
 #!/bin/bash
 
-# output dist directory name.
-DIRNAME_OUTPUT='output'
+set -eu
 
-# local directory settings.
-DIR_MOUNT_TARGET="$1"
-FILENAME_INPUT="$2"
-FILENAME_OUTPUT="$3"
 
-DIR_OUTPUT_DIST="${DIR_MOUNT_TARGET}/${DIRNAME_OUTPUT}"
+HOST_FILEPATH_INPUT="$1"
+HOST_FILEPATH_OUTPUT="$2"
+
+
+if !(type 'jq' > /dev/null 2>&1); then
+   echo "ERROR: \"jq\" command does not exist." 1>&2
+   echo "ERROR: Please install jq command" 1>&2
+   echo "ERROR: (ex)$ brew install jq" 1>&2
+
+   exit 1
+fi
+
+
+
+HOST_FILENAME_INPUT="$(basename "${HOST_FILEPATH_INPUT}")"
+HOST_FILENAME_OUTPUT="$(basename "${HOST_FILEPATH_OUTPUT}")"
+HOST_DIRNAME_INPUT="$(dirname "${HOST_FILEPATH_INPUT}")"
+HOST_DIRPATH_OUTPUT="$(dirname "${HOST_FILEPATH_OUTPUT}")"
+
+if [ ! -f "${HOST_FILEPATH_INPUT}" ]; then
+    echo ""${HOST_FILEPATH_INPUT}" does not exist." 1>&2
+    exit 1
+fi
+
+if [ ! -d "${HOST_DIRPATH_OUTPUT}" ]; then
+    echo ""${HOST_DIRPATH_OUTPUT}" does not exist." 1>&2
+    exit 1
+fi
+
+if [ -f "${HOST_FILEPATH_OUTPUT}" ]; then
+    echo "Same name file already exists at the output destination." 1>&2
+    exit 1
+fi
+
+
 
 # Docker container directory settings.
 DOCKER_IMAGE_FFMPEG='jrottenberg/ffmpeg'
-DOCKER_DIR_MOUNT_DIST='/ffmpeg'
-DOCKER_DIR_OUTPUT_DIST="/ffmpeg/${DIRNAME_OUTPUT}"
+DOCKER_DIRPATH_INPUT="/ffmpeg/input"
+DOCKER_DIRPATH_OUTPUT="/ffmpeg/output"
 
-INPUT_FILE_PATH="${DOCKER_DIR_MOUNT_DIST}/${FILENAME_INPUT}"
-OUTPUT_FILE_PATH="${DOCKER_DIR_OUTPUT_DIST}/${FILENAME_OUTPUT}"
-
-if !(type 'jq' > /dev/null 2>&1); then
-   echo "ERROR: jq command does not exist." 1>&2
-   echo "Please install jq command" 1>&2
-   echo "$ brew install jq" 1>&2
-
-   exit 1
-
-fi
-
-mkdir -p "${DIR_OUTPUT_DIST}"
+DOCKER_FILEPATH_INPUT="${DOCKER_DIRPATH_INPUT}/${HOST_FILENAME_INPUT}"
+DOCKER_FILEPATH_OUTPUT="${DOCKER_DIRPATH_OUTPUT}/${HOST_FILENAME_OUTPUT}"
 
 
 ebu_r128_general_value='I=-23:LRA=7:TP=-2.0'
 
-mp3_data_json="$(docker run --rm -t -v "${DIR_MOUNT_TARGET}":"${DOCKER_DIR_MOUNT_DIST}" "${DOCKER_IMAGE_FFMPEG}" -i "${INPUT_FILE_PATH}" -af loudnorm="${ebu_r128_general_value}":print_format=json -f null - | grep -A 100 -e '{' | grep -B 100 -e '}')"
+
+mp3_data_json="$(docker run --rm -t -v "${HOST_DIRNAME_INPUT}":"${DOCKER_DIRPATH_INPUT}" "${DOCKER_IMAGE_FFMPEG}" -i "${DOCKER_FILEPATH_INPUT}" -af loudnorm="${ebu_r128_general_value}":print_format=json -f null - | grep -A 100 -e '{' | grep -B 100 -e '}')"
 
 measured_i="$(echo "${mp3_data_json}" | jq '.input_i' | sed -e 's/"//g')"
 measured_tp="$(echo "${mp3_data_json}" | jq '.input_tp' | sed -e 's/"//g')"
@@ -44,6 +63,6 @@ EBU_R128_FILTER="${ebu_r128_general_value}:${measured_value}:linear=true:print_f
 SOUND_QUALITY=2
 
 
-docker run --rm -t -v "${DIR_MOUNT_TARGET}":"${DOCKER_DIR_MOUNT_DIST}" "${DOCKER_IMAGE_FFMPEG}" -i "${INPUT_FILE_PATH}" -af loudnorm="${EBU_R128_FILTER}" -codec:a libmp3lame -q:a "${SOUND_QUALITY}" -y "${OUTPUT_FILE_PATH}"
+docker run --rm -t -v "${HOST_DIRNAME_INPUT}":"${DOCKER_DIRPATH_INPUT}" -v "${HOST_DIRPATH_OUTPUT}":"${DOCKER_DIRPATH_OUTPUT}" "${DOCKER_IMAGE_FFMPEG}" -i "${DOCKER_FILEPATH_INPUT}" -af loudnorm="${EBU_R128_FILTER}" -codec:a libmp3lame -q:a "${SOUND_QUALITY}" -y "${DOCKER_FILEPATH_OUTPUT}"
 
 exit 0
